# Nama workflow yang akan muncul di tab Actions GitHub
name: Build kogito package

# Kondisi kapan workflow ini akan dijalankan
on:
  # 1. Saat sebuah release baru dibuat
  release:
    types: [created]

  # 2. Saat ada push ke branch 'dev'
  # Catatan: Ini akan mencoba 'deploy' setiap kali ada push ke dev.
  # Pertimbangkan untuk menghapus trigger 'push' jika deploy hanya diinginkan saat rilis.
  push:
    branches: [ "dev" ]

# Mendefinisikan satu atau lebih pekerjaan (jobs) yang akan dijalankan
jobs:
  # Nama job (bisa apa saja)
  build:
    # Menjalankan job ini di runner self-hosted Anda yang bernama 'runner1'
    runs-on: runner1

    # Izin yang diberikan kepada workflow. Cukup 'read' untuk checkout kode.
    permissions:
      contents: read

    # Langkah-langkah yang akan dieksekusi secara berurutan
    steps:
      # Langkah 1: Mengunduh kode dari repositori ke runner
      - name: Checkout repository code
        uses: actions/checkout@v4

      # Langkah 2: Menginstal JDK dan mengonfigurasi autentikasi Maven
      - name: Set up JDK 21 and Maven Central Authentication
        uses: actions/setup-java@v4
        with:
          # Menggunakan Java versi 21 dari Temurin
          java-version: '21'
          distribution: 'temurin'

          # Action ini akan membuat file settings.xml secara otomatis dengan detail berikut:
          # ID server harus cocok dengan <id> di dalam <distributionManagement> pada pom.xml
          server-id: central-portal-snapshots

          # Mengambil username dan password dari GitHub Secrets
          server-username: ${{ secrets.OSSRH_USERNAME }}
          server-password: ${{ secrets.OSSRH_TOKEN }}

      - name: Manually provide formatter config file
        run: cp kogito-build/kogito-ide-config/src/main/resources/eclipse-format.xml .
      # Langkah 3: Menjalankan build Maven (membersihkan, mengemas, dan melewati tes)
      - name: Build with Maven
        run: mvn -B clean package --file pom.xml -DskipTests -U

      # Langkah 4: Melakukan deploy artefak ke Sonatype Central
      # Tidak perlu flag '-s' karena settings.xml sudah otomatis dikonfigurasi oleh 'setup-java'
      - name: Publish to Sonatype Central
        run: mvn -B central-publishing:publish -U
